language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm install --global expo-cli
  - npm test
  - expo login -u $expo_username -p $expo_password
  - expo publish --non-interactive
