language: node_js
node_js:
  - node
  - lts/*
cache:
  directories:
    - ~/.npm
    - .jest
before_script:
  - npm install -g npm@latest
  - npm install
  - npm install jest-expo
  - npm install -g expo-cli
script:
  - npm ci
  - npx jest --ci
after-success:
  - npx expo login -u $expo_username -p $expo_password
  - npx expo publish --non-interactive
