export const mockCourses = [
  {
    department: 'Computer Science',
    number: '101',
    title: 'Computer Science: Concepts, Philosophy, and Connections',
    meets: 'MWF 11:00-11:50',
  },
  {
    department: 'Computer Science',
    number: '110',
    title: 'Intro Programming for non-majors',
    meets: 'MWF 10:00-10:50',
  },
  {
    department: 'Computer Science',
    number: '130',
    title: 'Tools and Technologies of the Web',
    meets: 'MW 16:00-16:50',
  },
  {
    department: 'Computer Science',
    number: '111',
    title: 'Fundamentals of Computer Programming I',
    meets: 'MWF 13:00-13:50',
  },
  {
    department: 'Computer Science',
    number: '211',
    title: 'Fundamentals of Computer Programming II',
    meets: 'TuTh 12:30-13:50',
  },
  {
    department: 'Computer Science',
    number: '212',
    title: 'Discrete math',
    meets: 'MWF 15:00-15:50',
  },
  {
    department: 'Computer Science',
    number: '213-1',
    title: 'Intro to systems',
    meets: 'TuTh 15:30-16:50',
  },
  {
    department: 'Computer Science',
    number: '214',
    title: 'Data structures',
    meets: 'TuTh 9:30-10:50',
  },
  {
    department: 'Computer Science',
    number: '217',
    title: 'Data management and information processing',
    meets: 'TuTh 12:30-13:50',
  },
  {
    department: 'Computer Science',
    number: '230',
    title: 'Programming for engineers',
    meets: 'TuTh 12:30-13:50',
  },
  {
    department: 'Computer Science',
    number: '295',
    title: 'IPD',
    meets: 'TuTh 11:00-13:50',
  },
  {
    department: 'Computer Science',
    number: '295',
    title: 'Fundamentals of Programming 1.5',
    meets: 'MWF 13:00-13:50',
  },
  {
    department: 'Computer Science',
    number: '313',
    title: 'Tangible Interaction Design and Learning',
    meets: 'TuTh 15:30-16:50',
  },
  {
    department: 'Computer Science',
    number: '314',
    title: 'Tech & Human Interaction',
    meets: 'TuTh 9:30-10:50',
  },
  {
    department: 'Computer Science',
    number: '321',
    title: 'Programming languages',
    meets: 'TuTh 11:00-12:20',
  },
  {
    department: 'Computer Science',
    number: '322',
    title: 'Compilers',
    meets: 'MWF 11:00-11:50',
  },
  {
    department: 'Computer Science',
    number: '323',
    title: 'Code Analysis and Transformation',
    meets: 'TuTh 12:30-13:50',
  },
  {
    department: 'Computer Science',
    number: '325',
    title: 'AI Programming',
    meets: 'MWF 11:00-11:50',
  },
  {
    department: 'Computer Science',
    number: '330',
    title: 'HCI',
    meets: 'MWF 13:00-13:50',
  },
  {
    department: 'Computer Science',
    number: '331',
    title: 'Intro. Computation Phototography',
    meets: 'TuTh 14:00-15:20',
  },
  {
    department: 'Computer Science',
    number: '336',
    title: 'Algorithms',
    meets: 'TuTh 15:30-16:50',
  },
  {
    department: 'Computer Science',
    number: '337',
    title: 'Semantic Information Processing',
    meets: 'MWF 11:00-11:50',
  },
  {
    department: 'Computer Science',
    number: '338',
    title: 'Practicum',
    meets: 'M 6:00-9:00',
  },
  {
    department: 'Computer Science',
    number: '339',
    title: 'Databases',
    meets: 'TuTh 15:30-16:50',
  },
  {
    department: 'Computer Science',
    number: '340',
    title: 'Networking',
    meets: 'MWF 16:00-16:50',
  },
  {
    department: 'Computer Science',
    number: '343',
    title: 'Operating Systems',
    meets: 'MWF 13:00-13:50',
  },
  {
    department: 'Computer Science',
    number: '345',
    title: 'Distributed Systems',
    meets: 'TuTh 9:00-10:20',
  },
  {
    department: 'Computer Science',
    number: '348',
    title: 'AI',
    meets: 'MWF 16:00-16:50',
  },
  {
    department: 'Computer Science',
    number: '349',
    title: 'ML',
    meets: 'MWF 16:00-16:50',
  },
  {
    department: 'Computer Science',
    number: '351-1',
    title: 'Intro graphics',
    meets: 'MWF 10:00-10:50',
  },
  {
    department: 'Computer Science',
    number: '351-2',
    title: 'Intermediate CG',
    meets: 'TuTh 9:30-10:50',
  },
  {
    department: 'Computer Science',
    number: '354',
    title: 'Network Penetration and Security',
    meets: 'TuTh 9:30-10:50',
  },
  {
    department: 'Computer Science',
    number: '371',
    title: 'Knowledge Representation and Reasoning',
    meets: 'TuTh 14:00-15:20',
  },
  {
    department: 'Computer Science',
    number: '376',
    title: 'Game Design and Development',
    meets: 'MWF 15:00-15:50',
  },
  {
    department: 'Computer Science',
    number: '397-1',
    title: 'Game Design Studio',
    meets: 'MW 18:00-19:30',
  },
  {
    department: 'Computer Science',
    number: '393',
    title: 'Software Construction',
    meets: 'TuTh 14:00-15:20',
  },
  {
    department: 'Computer Science',
    number: '394',
    title: 'Software Project Management and Development',
    meets: 'TuTh 11:00-12:20',
  },
  {
    department: 'Computer Science',
    number: '396-1',
    title: 'Introduction to cryptography',
    meets: 'MWF 15:00-15:50',
  },
  {
    department: 'Computer Science',
    number: '396-1',
    title: 'Swarms and Multi-Robot Systems',
    meets: 'TuTh 14:00-15:20',
  },
  {
    department: 'Computer Science',
    number: '396-1',
    title: 'Operational Semantics',
    meets: 'TuTh 12:30-13:50',
  },
  {
    department: 'Computer Science',
    number: '396-2',
    title: 'Quadrotor design and control',
    meets: 'Th 14:00-17:00',
  },
  {
    department: 'Computer Science',
    number: '396-3',
    title: 'Data Science Seminar',
    meets: 'TuTh 15:30-16:50',
  },
  {
    department: 'Computer Science',
    number: '396-2',
    title: 'Systems Programming in Rust',
    meets: 'TuTh 12:30-13:50',
  },
  {
    department: 'Computer Science',
    number: '396-3',
    title: 'Affective Computing Seminar',
    meets: 'TuTh 11:00-12:20',
  },
  {
    department: 'Computer Science',
    number: '396-4',
    title: 'Proving Properties of Programs',
    meets: 'TuTh 11:00-12:20',
  },
  {
    department: 'Computer Science',
    number: '396-4',
    title: 'Programming Language Seminar',
    meets: 'TuTh 12:30-13:50',
  },
  {
    department: 'Computer Science',
    number: '396-2',
    title: 'Advanced topics in compilers',
    meets: 'TuTh 9:30-10:50',
  },
  {
    department: 'Computer Science',
    number: '396-5',
    title: 'Topics in Software Engineering',
    meets: 'TuTh 3:30-4:50',
  },
  {
    department: 'Computer Science',
    number: '397-2',
    title: 'Digital Forensics',
    meets: 'MW 10:00-11:20',
  },
  {
    department: 'Computer Science',
    number: '397-3',
    title: 'Internet-Scale Experimentation',
    meets: 'MW 10:00-13:00',
  },
  {
    department: 'Computer Science',
    number: '397',
    title: 'Comp. Photography Seminar',
    meets: 'MWF 16:00-19:00',
  },
  {
    department: 'Computer Science',
    number: '397-4',
    title: 'Wireless and Mobile Health',
    meets: 'TuTh 5:00-6:20',
  },
  {
    department: 'Computer Science',
    number: '450',
    title: 'Internet Security',
    meets: 'TuTh 15:30-16:50',
  },
  {
    department: 'Computer Science',
    number: '446',
    title: 'Kernel and Other Low-level Software Development',
    meets: 'TuTh 9:30-10:50',
  },
  {
    department: 'Computer Science',
    number: '496-1',
    title: 'Special Topics in Game AI',
    meets: 'MWF 16:00-16:50',
  },
  {
    department: 'Computer Science',
    number: '496-1',
    title: 'Modern cryptography',
    meets: 'MWF 10:00-10:50',
  },
  {
    department: 'Computer Science',
    number: '473-1',
    title: 'NUVention Web+Media',
    meets: 'Tu 14:00-17:00',
  },
  {
    department: 'Computer Science',
    number: '496-2',
    title: 'Mechanism Design',
    meets: 'TuTh 9:30-10:50',
  },
  {
    department: 'Computer Science',
    number: '496-2',
    title: 'Approximation Algorithms',
    meets: 'TuTh 11:00-12:20',
  },
  {
    department: 'Computer Science',
    number: '496',
    title: 'Graduate Algorithms',
    meets: 'TuTh 15:30-16:50',
  },
];
